export const FETCH_DATA_REQUEST = 'FETCH_DATA_REQUEST'
export const FETCH_DATA_FAILURE = 'FETCH_DATA_FAILURE'
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS'

export const PRODUCT_DATA_REQUEST = 'PRODUCT_DATA_REQUEST'
export const PRODUCT_DATA_FAILURE = 'PRODUCT_DATA_FAILURE'
export const PRODUCT_DATA_SUCCESS = 'PRODUCT_DATA_SUCCESS'